[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
rootDirectory = "/degentrack"
