-- CreateTable
CREATE TABLE "TokenPeak" (
    "mint" TEXT NOT NULL,
    "peakMcUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "peakAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastCheckedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastMcUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "TokenPeak_pkey" PRIMARY KEY ("mint")
);
